PecanProject/bety

app/views/machines/_index_table.html.erb, app/views/machines/edit.html.erb, app/views/machines/show.html.erb, db/migrate/20150202190728_add_sync_id.rb
See https://github.com/PecanProject/pecan/issues/149
=> Add sync info to machines table

app/models/management.rb
updated management.rb controller to s/fertilization/fertilizer/ and also add fertilizer_%_rate option
refs #239
=> update managements controller for mgmttype

app/views/layouts/application.html.erb
@gsrohde please check that this looks okay, or perhaps we should find a matching icon from the redesign template ...
=> added gitter chat room icon / link to footer

app/models/workflow.rb, app/views/workflows/show.html.erb, db/migrate/20151011190026_add_notes_user_to_workflow.rb
update web to show notes and user
=> add notes and user to workflow

Rakefile
Now can run rake log db:migrate to see exact sql statement executed.
=> add log option to rakefile

app/views/workflows/_index_table.html.erb
=> fix wrong link

app/controllers/sites_controller.rb, app/helpers/sites_helper.rb, app/models/site.rb, app/views/sites/edit.html.erb
Fixes for GH issues #373 and #374.
=> Fixes for Site-geometry-releated problems

app/views/layouts/application.html.erb
Just a minor bit. I haven't looked to see if it looks okay.
created here: https://buttons.github.io/ using 'standard icon'
=> Adding Link to Github Button

app/models/ensemble.rb, app/models/input.rb, app/models/methods.rb, app/models/posteriors_ensembles.rb
@robkooper Could you look this over and see if you have any concerns?  I had to add these to get some of the API calls to work.
Also, I seem to recall there is one table whose name makes it look like a join table but it really isn't.  Which one was it?
=> Fixed some model associations.

.travis.yml, config/database.yml.travis
This will enable travis to auto build bety.
=> travis build

script/buildSQLGeom.py
Apply fixes suggested by @gsrohde to buildSQLGeom scripy.
=> Fixes to buildSQLGeom

db/migrate/20161005181021_add_score_benchmarks_ensembles_scores.rb
@bcow this should add the missing column
=> Add missing column #435

db/migrate/20160930213737_add_experiments_table.rb
@robkooper, @dlebauer Please check that this looks OK. See comments below.
=> Adding migration for creating experiments

db/migrate/20161129192658_database_change_requests.rb
@robkooper Could you check this over and see if it looks ok?
=> New migration to address issues #462 and #463.

app/views/variables/edit.html.erb, app/views/variables/new.html.erb
Added "Reflectance Index" as option for variable type
=> added Reflectance Index as variable type

db/migrate/20170415183619_add_sites_cultivars.rb
Code to add `sites_cultivars` table and related trigger functions.
=> Add sites cultivars

db/migrate/20170712171513_sites_cultivars_uniqueness.rb
@robkooper Please check that I got the sequence setting code right.
=> Fixed id sequence values for sites_cultivars table (issue #521).

Dockerfile, docker/database.yml, docker/entrypoint.sh
- cleanup of entrypoint, added more commands
- dockerfile cleanup, exposed database variables
- docker-compose.yml is now version 3
=> Cleanup of docker

app/controllers/api/v1/base_controller.rb, app/lib/utilities/sql_comments.rb, db/data/database_comments.yaml, lib/tasks/update_comments.rake
This implements the feature in issue #542 using YAML files and Rake tasks.
=> Sql comments rake task

app/models/bulk_upload_data_set.rb, spec/features/bulk_upload_integration_2_spec.rb
=> Bulk upload notes fix

.dockerignore, Dockerfile, app/helpers/application_helper.rb, docker/entrypoint.sh, hooks/build
- Pass git data as environment variables so no more need to copy .git folder
- Cleanup of Dockerfile and entrypoint.
hooks/build is what is executed by dockerhub to build the image.
=> More docker cleanup

Gemfile, Gemfile.lock
=> Updated two Gems.

app/views/covariates/show.html.erb
Changes the layout of the "Show" page for covariates.
=> Tidied up display of covariates (GH issue #280).

app/views/layouts/application.html.erb
This fixes #593
Replace the gitter button with a link to signup for slack.
=> Replace gitter with slack

CHANGELOG.md, docker-compose.yml, docker/entrypoint.sh
URL used to download initial version of BETY was wrong (used pecanall instead of pecan/all).
make sure to use latest in docker-compose not special tag.
=> fix download url and oter small docker fixes

CHANGELOG.md, app/helpers/application_helper.rb, hooks/build
This fixes issue #600.
This is a critical issue since it prevents the docker container from working.
=> create duplicate of environment variable

app/controllers/search_controller.rb
=> Fix for issue 618.

CHANGELOG.md, app/models/db_file.rb
A fix for a critical vulnerability reported by Danny Rosseau at Carve Systems (www.carvesystems.com).
=> Fix to make sure dbfiles have valid filename

README.md, app/views/layouts/application.html.erb, script/db_maintenance/README, script/load.bety.sh, spec/rails_helper.rb
reflecting migration to bookdown
=> update documentation links

.travis.yml, CHANGELOG.md, spec/rails_helper.rb
=> Fix method specification in bulk upload

CHANGELOG.md, Gemfile, Gemfile.lock
This replaces pull requests #673 and #675.
=> Changes to Gem files to fix issues 672 and 674.

.github/workflows/dbdump.yml
Upload to Docker hub was failing [very quietly](https://github.com/PecanProject/bety/runs/579843517?check_suite_focus=true#step:11:12).
=> typo in dump workflow

.github/pull.yml, .github/workflows/dbdump.yml, .gitignore, CHANGELOG.md, config/unicorn.rb, script/load.bety.sh
- added Wisconsin back to dump workflow
- more .gitignore fixes
- fork sync using https://wei.github.io/pull/
- cleanup after load.bety.sh stops unexpectedly
=> Small script updates
